// Generated by ego.
// DO NOT EDIT

package ego
import (
"fmt"
"html"
"io"
"strings"
)
//line _test\conents.ego:1
 func MyContents(w io.Writer, u *User) error  {
//line _test\conents.ego:2
_, _ = fmt.Fprint(w, "\n\n")
//line _test\conents.ego:4
_, _ = fmt.Fprint(w, "\n\n    <h1>Hello ")
//line _test\conents.ego:5
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.TrimSpace(u.FirstName) )))
//line _test\conents.ego:5
_, _ = fmt.Fprint(w, "!</h1>\n\n    <p>Here's a list of your favorite colors:</p>\n    <ul>\n      ")
//line _test\conents.ego:9
 for _, colorName := range u.FavoriteColors { 
//line _test\conents.ego:10
_, _ = fmt.Fprint(w, "\n        <li>")
//line _test\conents.ego:10
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  colorName )))
//line _test\conents.ego:10
_, _ = fmt.Fprint(w, "</li>\n      ")
//line _test\conents.ego:11
 } 
//line _test\conents.ego:12
_, _ = fmt.Fprint(w, "\n    </ul>\n\n")
//line _test\conents.ego:14
 EgoLayout(w, MyLayout) 
//line _test\conents.ego:15
_, _ = fmt.Fprint(w, "\n")
return nil
}
//line _test\layout.ego:1
 func MyLayout(w io.Writer, contents string) error  {
//line _test\layout.ego:2
_, _ = fmt.Fprint(w, "\n\n<html>\n  <body>\n     ")
//line _test\layout.ego:5
_, _ = fmt.Fprintf(w, "%v",  contents )
//line _test\layout.ego:6
_, _ = fmt.Fprint(w, "\n  </body>\n</html>\n")
return nil
}
//line _test\user.ego:1
 func UserView(w io.Writer, u *User) error  {
//line _test\user.ego:2
_, _ = fmt.Fprint(w, "\n\n")
//line _test\user.ego:4
_, _ = fmt.Fprint(w, "\n\n<html>\n  <body>\n    <h1>Hello ")
//line _test\user.ego:7
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.TrimSpace(u.FirstName) )))
//line _test\user.ego:7
_, _ = fmt.Fprint(w, "!</h1>\n\n    <p>Here's a list of your favorite colors:</p>\n    <ul>\n      ")
//line _test\user.ego:11
 for _, colorName := range u.FavoriteColors { 
//line _test\user.ego:12
_, _ = fmt.Fprint(w, "\n        <li>")
//line _test\user.ego:12
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  colorName )))
//line _test\user.ego:12
_, _ = fmt.Fprint(w, "</li>\n      ")
//line _test\user.ego:13
 } 
//line _test\user.ego:14
_, _ = fmt.Fprint(w, "\n    </ul>\n  </body>\n</html>\n")
return nil
}
